### PR TITLE
Add Run and Debug buttons to Spec Explorer

### PR DESCRIPTION
**Pull request by at6ue**
# Summary
Inline Run and Debug buttons in Spec Explorer to run/debug spec/scenario without opening files.
run and debug button in spec explorer

# Discussions
## Test codes
I could not add any tests for this because,
- Debug command tests could not wait for the debugger to detach.
- Scenario node tests will fail or work wrong after pack, because the `Scenario` class in the test code is not the same as the one in `extension.js`.

[Here's what I've done.](https://github.com/at6ue/gauge-vscode/blob/TEST_run-test-explorer-node/test/explorer/specExplorer.test.ts)

## Command contributions
Using `false` on when clause might confuse the parser, but I used `false` to respect the existing implementations.
https://github.com/microsoft/vscode/issues/45119

## Debugger starting failure
I modified `lineProcessor.ts` because I noticed VSCode show nothing there: `window.showErrorMessage` cannot handle `Error` object.
I was confused because the terminal only showed "Success: Tests passed." then. Is it intentional that passing `false` to `executor.cancel` here?

### CODE REVIEW

**Comment by sriv** [comment]
thanks for sending this, I will take a look shortly (held up on something else presently).

**Comment by sriv** [comment]
Something is up, I am trying to run [your tests] in my linux and macOS (m1) machines, and both yield the same error, ex:

```
 1) Spec Explorer Tests
       [MOCK]should run given specification node:
     TypeError: Cannot read property 'args' of undefined
  	at ArgCaptor.byCallIndex (node_modules/ts-mockito/lib/capture/ArgCaptor.js:26:36)
  	at ArgCaptor.last (node_modules/ts-mockito/lib/capture/ArgCaptor.js:20:21)
  	at /home/steam/projects/gauge-vscode/out/test/explorer/specExplorer.test.js:31:77
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/explorer/specExplorer.test.js:5:58)
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I am going to try again, but if this does not work, I'll test this manually and merge this in. This seems like a nice feature to have! Thanks for all the effort.

ps - your latest commit needs to be signed off, the DCO check is failing

**Comment by at6ue** [comment]
Thank you for the detail, I will look further into it this weekend, but perhaps we should focus on manual testing since test code are not good for production anyway.

I signed off the last commit and force pushed. I reset your merge commit so could you please merge master again if necessary?

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
@at6ue - thank you very much for adding this in! I have approved this, and marked this PR as a ReleaseCandidate. If you can please bump the version, I'll merge this in and it will trigger a release.

**Comment by at6ue** [comment]
>  TypeError: Cannot read property 'args' of undefined
>  	at ArgCaptor.byCallIndex (node_modules/ts-mockito/lib/capture/ArgCaptor.js:26:36)
>  	at ArgCaptor.last (node_modules/ts-mockito/lib/capture/ArgCaptor.js:20:21)
>  	at /home/steam/projects/gauge-vscode/out/test/explorer/specExplorer.test.js:31:77

This error seems to occur if the argument is captured before `mockExecutor.execute` is called.
`vscode.commands.executeCommand` just trigger the command that calls `mockExecutor.execute`, so perhaps the order of executions may change depending the environment...

Thank you for accepting. I bumped up the version, please check it.

PS: There is no [CONTRIBUTING.md](https://github.com/getgauge/gauge-vscode/blob/master/CONTRIBUTING.md) in this repo that gaugebot mentions.

**Comment by sriv** [comment]
> This error seems to occur if the argument is captured before mockExecutor.execute is called.
vscode.commands.executeCommand just trigger the command that calls mockExecutor.execute, so perhaps the order of executions may change depending the environment...

Possible, I will study this further.

> Thank you for accepting.

Thank you for improving gauge-vscode!

> PS: There is no CONTRIBUTING.md in this repo that gaugebot mentions.

Yes, some repositories do not have it. Gauge-bot is active across https://github.com/getgauge organization and hence it has a blanket message. Thanks for reminding - will put one in place!

**Pull request merged**
