### PR TITLE
do not look for java build tools for non-java projects

### PR DESCRIPTION
**Pull request by sriv**

### CODE REVIEW

**Comment by zabil** [comment]
@sriv can you bump up the version as this is marked as a release candidate?

**Comment by sriv** [comment]
@zabil - done. pls check.

**Comment by zabil** [comment]
@sriv @BugDiver It appears for publishing the package has expired and it wasn't able to deploy a new version to the Market place.

https://github.com/getgauge/gauge-vscode/runs/2819670936?check_suite_focus=true

I do not have the full context of how this was setup. Can either of you help me out. Perhaps we could move it to way that it's managed via GitHub organisation.

**Comment by sriv** [comment]
Looks like the vs marketplace token has expired. I'll take a look

**Pull request merged**
