### PR TITLE
moves client disposal into deactivate method

### PR DESCRIPTION
**Pull request by bockstaller**
Currently, LSP clients are disposed of within `gaugeWorkspace.ts` upon extension disposal.

This doesn't cover all cases and can leave the clients and server running.
I can observe this in our environment where `gauge-vscode` is deployed in a remote development setup. A window reload will dispose of all UI extensions but won't dispose of extensions running in the remote extension host mechanism, these are deactivated. 

The official [multi server LSP example](https://github.com/microsoft/vscode-extension-samples/blob/4721ef0c450f36b5bce2ecd5be4f0352ed9e28ab/lsp-multi-server-sample/client/src/extension.ts#L120) hoists the client map into `extension.ts` and explicitly disposes all resources on deactivation. 

This PR moves to this explicit deactivation strategy.

### CODE REVIEW

**Review by zabil — APPROVED** [review]

**Comment by bockstaller** [comment]
This might be fortunate as this release accidentally reduced backwards compatibility without need https://github.com/getgauge/gauge-vscode/pull/894 
Sorry for that

**Comment by chadlwilson** [comment]
@zabil Let me know if I can help in any way here. Note that there have been some other changes to `master` to address these issues so need to bump the version again (`0.1.2` or `0.2.0` I guess) with a new `ReleaseCandidate` before attempting again.

**Comment by zabil** [comment]
@sriv if you still have access to our 1password vault can you add @chadlwilson and @haroon-sheikh and re-add me? (i lost the master)

**Comment by haroon-sheikh** [comment]
That would be great! On a similar note, any of you know who's got access to this gradle plugin account's email (https://plugins.gradle.org/u/getgauge). I'd like to see if gradle have reviewed and responded about latest plugin's publish progress.

**Comment by sriv** [comment]
I do have access to 1pass. I will add you all to it. 

@haroon-sheikh - the gradle creds are available in the vault

**Comment by sriv** [comment]
@zabil - I have initiated your 1pass account recovery. @chadlwilson and @haroon-sheikh - I see that both of you are using your work email, I suspect 1pass for open source does not allow that :(

**Comment by haroon-sheikh** [comment]
@sriv Both of my personal and work emails are connected. Can you try sending an invite to haroon.sheikh@outlook.com

**Comment by haroon-sheikh** [comment]
Thanks @sriv. I've joined the getgauge team now. But don't have access to any vaults yet.

**Comment by sriv** [comment]
You should be set now @haroon-sheikh - i had to approve your membership

**Comment by haroon-sheikh** [comment]
Sorry to be a pain, I can see a shared vault now but no items unfortunately.

**Comment by bockstaller** [comment]
do y'all think you can fix the pipeline and publish a new release this week?

**Comment by zabil** [comment]
I will check it this week. The pipeline isn't working right now because the personal access tokens used to publish packages to VS Code have run out. So, I need to renew and update these tokens.

**Comment by zabil** [comment]
I think I've updated github actions to use correct access tokens. 

@bockstaller @chadlwilson, I want to confirm the version we're releasing. If my thoughts are correct, we might need to create a pull request to increase the version number since the last attempt to push the extension didn't work. Could one of you start a pull request that just changes the version number?

**Comment by bockstaller** [comment]
Will do

**Comment by bockstaller** [comment]
I am afraid merging the PR didn't create the release, but you are probably aware of that

**Comment by zabil** [comment]
Yes noticed that. And now I think I know why. I should've labelled the PR with the label "Release candidate" for it to trigger the release. Checking to see if I can trigger it without a PR.

**Comment by haroon-sheikh** [comment]
@zabil @bockstaller I've managed to trigger the deployment manually and can it was published successfully.

**Comment by zabil** [comment]
I see it's been successfull.

```

Publishing 'getgauge.gauge v0.1.3'...
Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=getgauge.gauge
Hub URL: https://marketplace.visualstudio.com/manage/publishers/getgauge/extensions/gauge/hub
Published getgauge.gauge v0.1.3.
```

But don't see a new version yet on https://marketplace.visualstudio.com/items?itemName=getgauge.gauge&ssr=false#version-history

I think it takes a some time to get published.

**Comment by zabil** [comment]
So I went to the extension list and saw this

```
Extension validation error
Error processing 'getgauge.gauge' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/version-short/getgauge.gauge.svg’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.
```

I'll send a PR to remove references to SVG. I think this is a recent change they did to the market place.

**Comment by bockstaller** [comment]
I would like to run some more tests tomorrow to catch any regressions. Maybe wait before publishing the next release until then

**Comment by bockstaller** [comment]
I am afraid I've found an issue regarding all the different vscode and lsp packages and their explicitly and implicitly required @types/vscode versions. 

This PR fixes it and should put an end to that trap:
https://github.com/getgauge/gauge-vscode/pull/899

**Pull request merged**
